BEGIN;
-- first i rename column id
ALTER TABLE STUDENTS
RENAME COLUMN ID TO STUDENT_ID;
-- then increase name column lenghts 
ALTER TABLE STUDENTS
ALTER COLUMN FIRSTNAME TYPE VARCHAR(40);

ALTER TABLE STUDENTS
ALTER COLUMN LASTNAME TYPE VARCHAR(40);

-- i create new table for the new structure
CREATE TABLE NEW_ACTIVITIES (
    STUDENT_ID INT,
    ACTIVITIES TEXT[],
    LEVELS TEXT[]
);

-- insert cleaned activities and remove duplicates , and also NULL values
INSERT INTO NEW_ACTIVITIES (STUDENT_ID, ACTIVITIES, LEVELS)
SELECT 
    s.STUDENT_ID,
    ARRAY_AGG(s.ACTIVITY),
    ARRAY_AGG(s.LEVEL)
FROM (
    SELECT DISTINCT STUDENT_ID, ACTIVITY, LEVEL
    FROM ACTIVITIES
    WHERE ACTIVITY IS NOT NULL 
      AND LEVEL IS NOT NULL
) s
GROUP BY s.STUDENT_ID;
