CREATE TABLE STUDENTS (
    ID INT,
    FIRSTNAME VARCHAR(20),
    LASTNAME VARCHAR(20)
);

CREATE TABLE ACTIVITIES (
    STUDENT_ID INT,
    ACTIVITY VARCHAR(25),
    LEVEL VARCHAR(10)
);

INSERT INTO STUDENTS VALUES
(1, 'James', 'Reyes'),
(2, 'Tiffany', 'Wolf'),
(3, 'David', 'Palmer');

INSERT INTO ACTIVITIES VALUES
(1, 'Tennis', 'Advanced'),
(1, 'Literature', 'Beginner'),
(1, 'Tennis', 'Advanced'),
(2, 'Football', 'Beginner'),
(3, 'Music', 'Advanced'),
(3, 'Chess', 'Beginner'),
(2, 'Tennis', 'Beginner'),
(1, 'Chemistry', 'Beginner'),
(3, 'Music', 'Advanced');

BEGIN;

-- First rename column id
ALTER TABLE STUDENTS
RENAME COLUMN ID TO STUDENT_ID;

-- Then increase name column lengths 
ALTER TABLE STUDENTS
ALTER COLUMN FIRSTNAME TYPE VARCHAR(40);

ALTER TABLE STUDENTS
ALTER COLUMN LASTNAME TYPE VARCHAR(40);

-- Create new table with PRIMARY KEY
CREATE TABLE NEW_ACTIVITIES (
    STUDENT_ID INT PRIMARY KEY,
    ACTIVITIES TEXT[],
    LEVELS TEXT[]
);

-- Insert cleaned activities and remove duplicates, NULL, empty, 
INSERT INTO NEW_ACTIVITIES (STUDENT_ID, ACTIVITIES, LEVELS)
SELECT 
    s.STUDENT_ID,
    ARRAY_AGG(s.ACTIVITY ORDER BY s.ACTIVITY),
    ARRAY_AGG(s.LEVEL ORDER BY s.ACTIVITY)
FROM (
    SELECT DISTINCT 
        STUDENT_ID, 
        TRIM(ACTIVITY) as ACTIVITY, 
        TRIM(LEVEL) as LEVEL
    FROM ACTIVITIES
    WHERE ACTIVITY IS NOT NULL 
      AND LEVEL IS NOT NULL
      AND TRIM(ACTIVITY) != ''
      AND TRIM(LEVEL) != ''
) s
GROUP BY s.STUDENT_ID;

-- Insert students with no activities with using NULL 
INSERT INTO NEW_ACTIVITIES (STUDENT_ID, ACTIVITIES, LEVELS)
SELECT STUDENT_ID, NULL, NULL
FROM STUDENTS
WHERE STUDENT_ID NOT IN (
    SELECT STUDENT_ID FROM NEW_ACTIVITIES WHERE STUDENT_ID IS NOT NULL
);

-- Replace old activities table with new one
DROP TABLE ACTIVITIES;

ALTER TABLE NEW_ACTIVITIES
RENAME TO ACTIVITIES; 

-- finish migration 
COMMIT;

-- Check result 
SELECT * FROM ACTIVITIES ORDER BY STUDENT_ID;
