BEGIN;

-- first students back to old format
ALTER TABLE STUDENTS RENAME COLUMN STUDENT_ID TO ID;
ALTER TABLE STUDENTS ALTER COLUMN FIRSTNAME TYPE VARCHAR(20);
ALTER TABLE STUDENTS ALTER COLUMN LASTNAME  TYPE VARCHAR(20);

-- then create again old activities table
CREATE TABLE OLD_ACTIVITIES (
  STUDENT_ID INT,
  ACTIVITY   VARCHAR(25),
  LEVEL      VARCHAR(10)
);

-- convert arrays to rows 
INSERT INTO OLD_ACTIVITIES (STUDENT_ID, ACTIVITY, LEVEL)
SELECT
  a.STUDENT_ID,
  x.act,
  x.lvl
FROM ACTIVITIES a
CROSS JOIN LATERAL unnest(a.ACTIVITIES, a.LEVELS) AS x(act, lvl);

-- replace new table with old one
DROP TABLE ACTIVITIES;
ALTER TABLE OLD_ACTIVITIES RENAME TO ACTIVITIES;

--finish rollback
COMMIT;

-- check result 
SELECT * FROM ACTIVITIES ORDER BY STUDENT_ID, ACTIVITY;
