BEGIN;
-- make old table 
CREATE TABLE ACTIVITIES_OLD (
    STUDENT_ID INT,
    ACTIVITY VARCHAR(25),
    LEVEL VARCHAR(10)
);
-- convert  into rows
INSERT INTO OLD_ACTIVITIES (STUDENT_ID, ACTIVITY, LEVEL)
SELECT 
    STUDENT_ID,
    UNNEST(ACTIVITIES),
    UNNEST(LEVELS)
FROM ACTIVITIES; 
