BEGIN;
-- make old table 
CREATE TABLE ACTIVITIES_OLD (
    STUDENT_ID INT,
    ACTIVITY VARCHAR(25),
    LEVEL VARCHAR(10)
);
-- convert  into rows
INSERT INTO OLD_ACTIVITIES (STUDENT_ID, ACTIVITY, LEVEL)
SELECT 
    STUDENT_ID,
    UNNEST(ACTIVITIES),
    UNNEST(LEVELS)
FROM ACTIVITIES; 

-- remove our new structure 
DROP TABLE ACTIVITIES;

-- then i  rename table back to original name 
ALTER TABLE OLD_ACTIVITIES
RENAME TO ACTIVITIES;

-- rename again column back
ALTER TABLE STUDENTS
RENAME COLUMN STUDENT_ID TO ID;

-- restore original column sizes
ALTER TABLE STUDENTS
ALTER COLUMN FIRSTNAME TYPE VARCHAR(20);

ALTER TABLE STUDENTS
ALTER COLUMN LASTNAME TYPE VARCHAR(20);
